# Dataanalys #

Här går vi igenom datan som vi hämtar från rikstans databas som kommer att användas för att träna modellerna.

In [1]:
import numpy as np
import pandas as pd

In [2]:
members.info()
print(members.head())
print(members['parti'].unique())

NameError: name 'members' is not defined

In [3]:
anforande_202324 = pd.read_csv(
    'documents/anforande-202324.csv',
    header=0,
    names = [
    'dok_id', 
    'dok_rm', 
    'dok_nummer', 
    'dok_datum', 
    'avsnittsrubrik', 
    'kammaraktivitet', 
    'anforande_nummer', 
    'talare', 
    'parti', 
    'intressent_id', 
    'rel_dok_id', 
    'replik'],
    dtype={
        'intressent_id': 'string'
    }
) 
anforande_202324["dok_id"].unique()

array(['HB09100', 'HB09101', 'HB09102', 'HB09103', 'HB09104', 'HB09105',
       'HB09106', 'HB09107', 'HB09108', 'HB09109', 'HB0911', 'HB09110',
       'HB09111', 'HB09112', 'HB09113', 'HB09114', 'HB09115', 'HB09116',
       'HB09117', 'HB09118', 'HB09119', 'HB0912', 'HB09120', 'HB09121',
       'HB09122', 'HB09123', 'HB09124', 'HB09125', 'HB09126', 'HB09128',
       'HB09129', 'HB0913', 'HB09130', 'HB09131', 'HB09132', 'HB09133',
       'HB09134', 'HB09135', 'HB09136', 'HB09137', 'HB09138', 'HB09139',
       'HB09140', 'HB09141', 'HB0915', 'HB0916', 'HB0917', 'HB0918',
       'HB0919', 'HB092', 'HB0920', 'HB0921', 'HB0922', 'HB0923',
       'HB0924', 'HB0925', 'HB0926', 'HB0927', 'HB0928', 'HB0929',
       'HB093', 'HB0930', 'HB0931', 'HB0932', 'HB0933', 'HB0934',
       'HB0935', 'HB0936', 'HB0937', 'HB0938', 'HB0939', 'HB094',
       'HB0940', 'HB0941', 'HB0942', 'HB0943', 'HB0944', 'HB0945',
       'HB0946', 'HB0947', 'HB0948', 'HB0949', 'HB095', 'HB0950',
       'HB0951', 'HB0952', 'HB0953', 'HB0954', 'HB0955', 'HB0956',
       'HB0957', 'HB0958', 'HB0959', 'HB096', 'HB0960', 'HB0961',
       'HB0962', 'HB0963', 'HB0964', 'HB0965', 'HB0966', 'HB0967',
       'HB0968', 'HB0969', 'HB097', 'HB0970', 'HB0971', 'HB0972',
       'HB0973', 'HB0975', 'HB0976', 'HB0977', 'HB0978', 'HB0979',
       'HB098', 'HB0980', 'HB0981', 'HB0982', 'HB0983', 'HB0984',
       'HB0985', 'HB0986', 'HB0987', 'HB0988', 'HB0989', 'HB099',
       'HB0990', 'HB0991', 'HB0992', 'HB0993', 'HB0994', 'HB0995',
       'HB0996', 'HB0997', 'HB0998', 'HB0999'], dtype=object)

In [18]:
print(anforande_202324[anforande_202324["dok_id"] == "HB09124"])

       dok_id   dok_rm  dok_nummer            dok_datum  \
2954  HB09124  2023/24         124  2024-05-29 00:00:00
2955  HB09124  2023/24         124  2024-05-29 00:00:00
2956  HB09124  2023/24         124  2024-05-29 00:00:00
2957  HB09124  2023/24         124  2024-05-29 00:00:00
2958  HB09124  2023/24         124  2024-05-29 00:00:00
...       ...      ...         ...                  ...
3028  HB09124  2023/24         124  2024-05-29 00:00:00
3029  HB09124  2023/24         124  2024-05-29 00:00:00
3030  HB09124  2023/24         124  2024-05-29 00:00:00
3031  HB09124  2023/24         124  2024-05-29 00:00:00
3032  HB09124  2023/24         124  2024-05-29 00:00:00

                                         avsnittsrubrik kammaraktivitet  \
2954  Vissa förslag om kompensation m.m. till person...    ärendedebatt
2955  Vissa förslag om kompensation m.m. till person...    ärendedebatt
2956  Vissa förslag om kompensation m.m. till person...    ärendedebatt
2957  Vissa förslag om kompensation m.m. till person...    ärendedebatt
2958  Vissa förslag om kompensation m.m. till person...    ärendedebatt
...                                                 ...             ...
3028  Riksrevisionens rapport om systemet för återka...    ärendedebatt
3029  Riksrevisionens rapport om systemet för återka...    ärendedebatt
3030  Riksrevisionens rapport om systemet för återka...    ärendedebatt
3031  Vissa förslag om kompensation m.m. till person...    ärendedebatt
3032  Vissa förslag om kompensation m.m. till person...    ärendedebatt

      anforande_nummer                 talare                  parti  \
2954                 1      Patrik Björck (S)                      S
2955                10      Patrik Björck (S)                      S
2956                11    Erik Hellsborn (SD)                     SD
2957                12   Crister Carlsson (M)                      M
2958                13      Patrik Björck (S)                      S
...                ...                    ...                    ...
3028                77   Annika Hirvonen (MP)                     MP
3029                78     Mauricio Rojas (L)                      L
3030                79   Annika Hirvonen (MP)                     MP
3031                 8  TREDJE VICE TALMANNEN  TREDJE VICE TALMANNEN
3032                 9   Crister Carlsson (M)                      M

      intressent_id rel_dok_id replik
2954  0516528386117  HB01SkU23      N
2955  0516528386117  HB01SkU23      Y
2956  0362779191527  HB01SkU23      N
2957  0387230530213  HB01SkU23      N
2958  0516528386117  HB01SkU23      Y
...             ...        ...    ...
3028  0819601620927  HB01SfU17      Y
3029  0591055036519  HB01SfU17      Y
3030  0819601620927  HB01SfU17      Y
3031  0155487380917  HB01SkU23      N
3032  0387230530213  HB01SkU23      Y

[79 rows x 12 columns]

In [8]:
anforande_202223

,dok_id,dok_rm,dok_nummer,dok_datum,avsnittsrubrik,kammaraktivitet,anforande_nummer,talare,parti,intressent_id,rel_dok_id,replik
0,HA091,2022/23,1,2022-09-26 00:00:00,Val av förste vice talman,NaN,10,Gunilla Carlsson (S),S,0875221317013,NaN,N
1,HA091,2022/23,1,2022-09-26 00:00:00,Val av förste vice talman,NaN,11,Annie Lööf (C),C,0862868280923,NaN,N
2,HA091,2022/23,1,2022-09-26 00:00:00,Val av andre vice talman,NaN,12,Henrik Vinge (SD),SD,0406831930624,NaN,N
3,HA091,2022/23,1,2022-09-26 00:00:00,Val av andre vice talman,NaN,13,Annika Hirvonen (MP),MP,0819601620927,NaN,N
4,HA091,2022/23,1,2022-09-26 00:00:00,Val av andre vice talman,NaN,14,SAMUEL GONZALEZ WESTLING (V),V,<NA>,NaN,N
...,...,...,...,...,...,...,...,...,...,...,...,...
12474,HA0999,2022/23,99,2023-04-27 00:00:00,Frågestund,frågestund,95,Per-Arne Håkansson (S),S,0630820052511,HAC120230427fs,N
12475,HA0999,2022/23,99,2023-04-27 00:00:00,Frågestund,frågestund,96,Energi- och näringsministern Ebba Busch (KD),KD,0512510717328,HAC120230427fs,N
12476,HA0999,2022/23,99,2023-04-27 00:00:00,Frågestund,frågestund,97,Carita Boulwén (SD),SD,0371882294919,HAC120230427fs,N
12477,HA0999,2022/23,99,2023-04-27 00:00:00,Frågestund,frågestund,98,Statsrådet Anna Tenje (M),M,0476336341120,HAC120230427fs,N
12478,HA0999,2022/23,99,2023-04-27 00:00:00,Frågestund,frågestund,99,Malin Larsson (S),S,0203877548421,HAC120230427fs,N

In [5]:
votering_202223 = pd.read_csv('documents/votering-202223.csv')
votering_202223.info()
print(votering_202223.columns)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 196835 entries, 0 to 196834
Data columns (total 14 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   2022/23                               196835 non-null  object
 1   UU15                                  196835 non-null  object
 2   008484EA-7970-4559-BEA7-E2F6454E7571  196835 non-null  object
 3   5                                     196835 non-null  int64
 4   Julia Kronlid                         196835 non-null  object
 5   0638497389621                         196835 non-null  int64
 6   SD                                    196835 non-null  object
 7   Stockholms län                        196835 non-null  object
 8   Frånvarande                           196835 non-null  object
 9   sakfrågan                             196835 non-null  object
 10  2                                     196835 non-null  int64
 11  kvinna                                196835 non-null  object
 12  1980                                  196835 non-null  int64
 13  2023-05-10                            196835 non-null  object
dtypes: int64(4), object(10)
memory usage: 21.0+ MB
Index(['2022/23', 'UU15', '008484EA-7970-4559-BEA7-E2F6454E7571', '5',
       'Julia Kronlid', '0638497389621', 'SD', 'Stockholms län', 'Frånvarande',
       'sakfrågan', '2', 'kvinna', '1980', '2023-05-10'],
      dtype='object')

In [6]:
votering_columns = [
    'rm',
    'beteckning',
    'votering_id',
    'punkt',
    'namn',
    'intressent_id',
    'parti',
    'valkrets',
    'rost',
    'avser',
    'banknummer',
    'kön',
    'fodd',
    'system_datum'
]
votering_202223 = pd.read_csv(
    'documents/votering-202223.csv',
    header=0,
    names=votering_columns,
    dtype={ 'intressent_id': 'string' }
)

votering_202223

,rm,beteckning,votering_id,punkt,namn,intressent_id,parti,valkrets,rost,avser,banknummer,kön,fodd,system_datum
0,2022/23,UU15,008484EA-7970-4559-BEA7-E2F6454E7571,5,Helena Bouveng,0729710260118,M,Jönköpings län,Ja,sakfrågan,10,kvinna,1962,2023-05-10
1,2022/23,UU15,008484EA-7970-4559-BEA7-E2F6454E7571,5,Mattias Jonsson,0499755198526,S,Göteborgs kommun,Ja,sakfrågan,18,man,1974,2023-05-10
2,2022/23,UU15,008484EA-7970-4559-BEA7-E2F6454E7571,5,Merit Frost Lindberg,0533104339313,M,Stockholms kommun,Ja,sakfrågan,26,kvinna,1973,2023-05-10
3,2022/23,UU15,008484EA-7970-4559-BEA7-E2F6454E7571,5,Jimmie Åkesson,051207517226,SD,Jönköpings län,Frånvarande,sakfrågan,34,man,1979,2023-05-10
4,2022/23,UU15,008484EA-7970-4559-BEA7-E2F6454E7571,5,Maj Karlsson,0198917587520,V,Göteborgs kommun,Frånvarande,sakfrågan,42,kvinna,1980,2023-05-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196830,2022/23,CU6,FFC81C4F-0CB8-4972-A18D-4E4C62BFC19B,23,Carl B Hamilton,0477013214601,L,Stockholms kommun,Frånvarande,sakfrågan,316,man,1946,2023-04-19
196831,2022/23,CU6,FFC81C4F-0CB8-4972-A18D-4E4C62BFC19B,23,Rebecka Le Moine,0546731406922,MP,Östergötlands län,Avstår,sakfrågan,324,kvinna,1990,2023-04-19
196832,2022/23,CU6,FFC81C4F-0CB8-4972-A18D-4E4C62BFC19B,23,Emma Ahlström Köster,0360160202728,M,Skåne läns södra,Ja,sakfrågan,332,kvinna,1987,2023-04-19
196833,2022/23,CU6,FFC81C4F-0CB8-4972-A18D-4E4C62BFC19B,23,Camilla Hansén,0692076685824,MP,Örebro län,Avstår,sakfrågan,340,kvinna,1976,2023-04-19
196834,2022/23,CU6,FFC81C4F-0CB8-4972-A18D-4E4C62BFC19B,23,Peter Hedberg,0589561178823,S,Västernorrlands län,Nej,sakfrågan,348,man,1990,2023-04-19

In [7]:
votering_202223.columns = [
    'rm',
    'beteckning',
    'votering_id',
    'punkt',
    'namn',
    'intressent_id',
    'parti',
    'valkrets',
    'rost',
    'avser',
    'banknummer',
    'kön',
    'fodd',
    'system_datum'
]

votering_202223

,rm,beteckning,votering_id,punkt,namn,intressent_id,parti,valkrets,rost,avser,banknummer,kön,fodd,system_datum
0,2022/23,UU15,008484EA-7970-4559-BEA7-E2F6454E7571,5,Helena Bouveng,0729710260118,M,Jönköpings län,Ja,sakfrågan,10,kvinna,1962,2023-05-10
1,2022/23,UU15,008484EA-7970-4559-BEA7-E2F6454E7571,5,Mattias Jonsson,0499755198526,S,Göteborgs kommun,Ja,sakfrågan,18,man,1974,2023-05-10
2,2022/23,UU15,008484EA-7970-4559-BEA7-E2F6454E7571,5,Merit Frost Lindberg,0533104339313,M,Stockholms kommun,Ja,sakfrågan,26,kvinna,1973,2023-05-10
3,2022/23,UU15,008484EA-7970-4559-BEA7-E2F6454E7571,5,Jimmie Åkesson,051207517226,SD,Jönköpings län,Frånvarande,sakfrågan,34,man,1979,2023-05-10
4,2022/23,UU15,008484EA-7970-4559-BEA7-E2F6454E7571,5,Maj Karlsson,0198917587520,V,Göteborgs kommun,Frånvarande,sakfrågan,42,kvinna,1980,2023-05-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196830,2022/23,CU6,FFC81C4F-0CB8-4972-A18D-4E4C62BFC19B,23,Carl B Hamilton,0477013214601,L,Stockholms kommun,Frånvarande,sakfrågan,316,man,1946,2023-04-19
196831,2022/23,CU6,FFC81C4F-0CB8-4972-A18D-4E4C62BFC19B,23,Rebecka Le Moine,0546731406922,MP,Östergötlands län,Avstår,sakfrågan,324,kvinna,1990,2023-04-19
196832,2022/23,CU6,FFC81C4F-0CB8-4972-A18D-4E4C62BFC19B,23,Emma Ahlström Köster,0360160202728,M,Skåne läns södra,Ja,sakfrågan,332,kvinna,1987,2023-04-19
196833,2022/23,CU6,FFC81C4F-0CB8-4972-A18D-4E4C62BFC19B,23,Camilla Hansén,0692076685824,MP,Örebro län,Avstår,sakfrågan,340,kvinna,1976,2023-04-19
196834,2022/23,CU6,FFC81C4F-0CB8-4972-A18D-4E4C62BFC19B,23,Peter Hedberg,0589561178823,S,Västernorrlands län,Nej,sakfrågan,348,man,1990,2023-04-19

In [8]:
anforande_202223.loc[1]

dok_id                                  HA091
dok_rm                                2022/23
dok_nummer                                  1
dok_datum                 2022-09-26 00:00:00
avsnittsrubrik      Val av förste vice talman
kammaraktivitet                           NaN
anforande_nummer                           11
talare                         Annie Lööf (C)
parti                                       C
intressent_id                   0862868280923
rel_dok_id                                NaN
replik                                      N
Name: 1, dtype: object

In [11]:
print(len(anforande_202324[0]))

KeyError: 0

In [12]:
text = "HB09100	2023/24	100	2024-04-17 00:00:00	Förbättrade möjligheter att ändra kön	ärendedebatt	1	Yasmine Bladelius (S)	S	0996640018922	HB01SoU22	N"
print(len(text))

142

In [12]:
from api_caller import fetch_document_html
from langchain_community.document_transformers import BeautifulSoupTransformer
from langchain_core.documents import Document

def get_documents(dok_ids: list[str]) -> list[dict[str, str]]:
    """
    Fetches documents by their IDs and returns a list of dictionaries containing the document content.
    """
    documents = []
    bs_transformer = BeautifulSoupTransformer()
    
    try:
        if not isinstance(dok_ids, list):
            print("Invalid input: dok_ids must be a list.")
            raise TypeError("dok_ids must be a list.")
        if len(dok_ids) == 0:
            print("No document IDs provided.")
            raise ValueError("No document IDs provided.")
        else:        
            for dok_id in dok_ids:
                document = {}
                fetched_doc = fetch_document_html(dok_id)
                cleaned = bs_transformer.transform_documents([fetched_doc], tags_to_extract=["p", "h1", "h2", "h3", "li"])

                document["dok_id"] = dok_id
                document["innehåll"] = cleaned[0].page_content

                documents.append(document)

            return documents
    
    except Exception as e:
        print(f"Error fetching documents: {e}")

documents = get_documents("sgf")
print(documents)

Invalid input: dok_ids must be a list.
Error fetching documents: dok_ids must be a list.
None

In [3]:
personer = pd.read_csv("documents/personer/personer")

personer.columns

Index(['Förnamn', 'Efternamn', 'Iort', 'Parti', 'Id', 'Kön', 'Född',
       'Valkrets', 'Status', 'Webbadress', 'Epostadress', 'Telefonnummer',
       'Titel', 'Uppdragstyp', 'Uppdragsorgan', 'Uppdragsroll',
       'Uppdragsrollstatus', 'From', 'Tom'],
      dtype='object')

In [22]:
columns = {
    'Förnamn': 'förnamn',
    'Efternamn': 'efternamn',
    'Parti': 'parti',
    'Id': 'intressent_id',
    'Kön': 'kön',
    'Född': 'född',
    'Valkrets': 'valktrets',

}

cleaned = pd.read_csv("documents/personer/personer", header=0, usecols=columns)

cleaned_copy = cleaned.rename(columns=columns).drop_duplicates(subset=['intressent_id']).copy()

cleaned_copy.info()

<class 'pandas.core.frame.DataFrame'>
Index: 349 entries, 0 to 8723
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   förnamn        349 non-null    object
 1   efternamn      349 non-null    object
 2   parti          349 non-null    object
 3   intressent_id  349 non-null    int64
 4   kön            349 non-null    object
 5   född           349 non-null    int64
 6   valktrets      349 non-null    object
dtypes: int64(2), object(5)
memory usage: 21.8+ KB

In [21]:
DATABASE_URL = "postgresql+psycopg2://gov_check_user:gov_check_pw@localhost:5432/gov_check_db"

from sqlalchemy import create_engine, text
from sqlalchemy.orm import sessionmaker

engine = create_engine(
    DATABASE_URL,
    pool_size=5,
    max_overflow=10,
    pool_pre_ping=True
)

SessionLocal = sessionmaker(
    autocommit=False,
    autoflush=False,
    bind=engine
)

# with SessionLocal() as session:
#     with session.begin():
#         session.execute(text("INSERT INTO votering (rm,beteckning,hangar_id,votering_id,punkt,namn,intressent_id,parti,valkrets,valkretsnummer,iort,rost,avser,votering,banknummer,fornamn,efternamn,kon,fodd,datum) VALUES ('2022/23','UU15',5167346,'008484EA-7970-4559-BEA7-E2F6454E7571',5,'Merit Frost Lindberg','0533104339313','M','Stockholms kommun',1,'','Ja','sakfrågan','huvud',26,'Merit','Frost Lindberg','kvinna',1973,'2023-05-10');"))


# Instantiate a session, then call .begin() on it
with SessionLocal() as sess:
    with sess.begin():
        result = sess.scalars(text("SELECT embedding FROM person LIMIT 2"))
        print(result.all())

['[0.025676053,-0.0026329507,0.010524441,0.06965817,-0.0050727036,-0.037621234,0.024919631,-0.008695321,-0.026588326,-0.0007942913,0.049374256,-0.0067007616,0.028564176,0.0043143434,-0.03060792,-0.065526314,0.019550378,0.017487584,-0.039273325,-0.023817152,0.006434499,0.036852334,-0.012560278,0.049656097,0.059719186,0.008552588,-0.01636966,-0.0027456766,0.06318743,0.049733367,0.023697622,-0.06484016,-0.006996954,-0.004304735,1.6542198e-06,0.044771045,0.02459897,0.005493201,-0.04126864,0.008162664,-0.037635505,0.026822386,-0.05992357,-0.009109119,0.02402218,0.00887239,-0.01629485,-0.002573683,-0.030336395,-0.0126960995,0.009088868,0.023806853,-0.014360338,-0.016223475,0.039107658,-0.04444122,0.023239633,0.009494739,-0.0047867834,0.025640098,0.016563945,0.0305717,-0.019848108,0.017868806,-0.01174228,0.026891522,0.03920005,-0.04309983,-0.0011769118,0.0476268,0.11177799,0.0009535743,0.035141908,0.057194393,-0.022767415,0.042575657,-0.009118025,-0.029875416,-0.048883844,-0.014956226,0.012561536,-0.0009363894,-0.0209415,0.044392556,0.019527288,-0.01247695,-0.017882507,-0.0149086695,-0.00046555814,-0.03957106,-0.018550476,-0.0015371067,-0.017775359,-0.0063204286,-0.001990067,-0.01952553,0.022156896,-0.092161074,0.045633852,-0.052603763,-0.067775905,0.0053033093,-0.0027816799,0.042997845,0.04877819,-0.028414845,-0.010485018,0.022671636,-0.0012452884,-0.0018165031,0.028378867,0.0065251384,-0.0064011975,-0.010436983,-0.008870599,0.034289327,-0.06222219,0.025545627,0.032946434,0.020683253,-0.0013979838,-0.0018391963,-0.0128545845,0.0023911349,-0.036890145,0.0034646303,-0.00083702576,0.0066618854,-0.034561776,0.024331043,0.037407868,0.041538067,0.009282178,-0.010520107,0.0339086,0.03371376,-0.06564813,-0.036396865,0.09851382,0.030604953,0.039711233,-0.032809224,0.01715617,0.00271552,-0.009503318,0.014273627,-0.020066747,-0.011420927,-0.01776548,-0.027777025,-0.0070054745,-0.022541847,-0.004854176,0.008369014,0.08680168,0.012263226,0.0021888071,-0.04601152,-0.048441,-0.011615292,-0.020969132,-0.026394809,-0.013119666,0.039651062,0.024865098,-0.020443453,0.04653123,0.048788767,-0.07335151,-0.05139917,0.0048410557,-0.008173839,-0.0017209402,0.0100794835,-0.013796717,0.022378387,0.015154913,-0.0011249001,-0.020577606,0.030202892,0.0066244463,-0.12288748,0.0045452733,-0.0015700135,0.034734026,0.0141322,0.015262354,0.0318188,0.0396751,-0.0014333826,0.06840682,0.018938506,-0.029971363,0.05622125,-0.015890656,-0.024881866,-0.030281285,0.053089533,-0.02074342,0.0060262308,0.05443936,-0.03758904,-0.023711124,-0.0047380836,-0.03402904,0.0018426708,-0.01313875,-0.041849975,-0.030842064,-0.00044009436,0.050796095,0.012696352,-0.013693691,0.019682396,0.024385573,0.07145405,-0.00957742,0.07364035,-0.035955876,0.02834637,-0.01053653,0.007302304,0.022755679,-0.026672676,0.036799856,0.025659895,-0.09018693,-0.010641039,-0.005193977,0.035481267,-0.008786279,0.018015735,0.033987958,-0.032653145,-0.017495226,0.022594826,0.10222007,-0.08125493,-0.0032730184,-0.042432282,-0.03011537,0.0570629,0.011220054,-0.008510449,0.08461044,0.031808335,-0.04914831,-0.01063836,0.006422736,-0.017087262,-0.019757641,-0.0047560064,0.021410316,-0.011125594,0.0051180026,-0.017125422,-0.027765088,-0.0096461605,-0.10174505,-0.0078178095,0.02709491,0.00204699,0.030426955,-0.0037897204,0.014088771,-0.001177364,-0.029443465,0.023924708,-0.057371814,-0.048740003,0.028464332,0.020724123,0.04347881,-0.010429727,-0.009902917,-0.010802548,0.017536255,0.020873172,-0.0035016024,-0.0012039302,0.010782303,-0.065662995,-0.017874818,-0.030453721,-0.02189652,-0.032937456,0.012073671,-0.09476084,0.02744898,-0.029638888,-0.046175595,-0.0322226,-0.009072509,-0.023825752,0.023190351,0.009212963,-0.017403442,0.037580084,-0.0020339864,0.025099311,-0.028389402,0.029169267,-0.03295937,-0.013201108,-0.03239667,0.051494163,-0.007923908,0.05578559,0.010212779,-0.03711565,0.0011587164,0.035019126,0.034886472,-0.04171405,0.061517686,0.05705742,-0.09127253,-0.043128677,0.0024572678,0.10190923,0.031808343,0.021077933,-0.034357827,-0.0055875196,0.011863733,-0.0065346756,-0.05896662,-0.010308254,0.0336478,-0.03239336,0.047678947,-0.088752694,0.019616505,0.042813316,-0.091270246,-0.011355785,-0.027687142,-0.03131228,0.03381424,0.015702566,-0.043508887,-0.047467414,-0.016370514,-0.016499616,-0.065733455,-0.05555903,-0.07085171,0.08065389,-0.031357102,-0.039049156,-0.042262916,0.0019230883,-0.008010015,0.033296317,-0.021563897,-0.0021053415,-0.013094,-0.022478051,-0.0694334,0.036275696,-0.031252947,-0.040635917,-0.06859383,0.04240955,0.021063836,0.025155434,0.0368717,0.012156084,-0.016122077,-0.033430297,0.06363603,-0.024606083,0.0040516797,0.0055967565,-0.007823579,-0.043755084,0.008723022,-0.0124718165,0.028625818,0.015924985,0.03250799,-0.021229971,0.050451957,-0.012137805,0.0047049895,-0.06448536,-0.0030346294,-0.011115643,0.034800846,0.017745078,0.020110054,-0.09502714,-0.012163257,0.0084330505,-0.00812975,-0.03356898,0.05836404,0.009479753,0.036852952,0.020898,-0.0148900645,-0.031306487,-0.044327065,0.060488213,-0.018560627,0.04190767,0.032327794,0.05345093,0.027387073,-0.039005928,0.056005757,0.03473871,-0.016120143,0.011145188,-0.030159345,-0.07401562,-0.0059043015,-0.036530085,0.06691241,0.05164353,-0.039439715,0.01599525,0.00091985846,-0.0060518133,0.079755016,0.02655082,0.08303612,0.073693044,-0.022117278,0.043362476,0.06303184,-0.041143868,-0.058492437,0.022773782,0.0280994,-0.02338645,-0.011060078,0.046102956,0.013921859,0.026084162,-0.027354239,0.04001743,0.037174705,-0.007825298,-0.014012531,0.042012114,0.018130697,-0.0022238346,-0.035521682,-0.005650187,0.019286329,0.030280964,0.009427074,0.021504864,0.040904135,-0.02150589,-0.035680927,-0.0064501395,-0.01905188,0.028892567,-0.02327321,0.039854117,0.06073601,-0.01820225,0.0020016585,-0.057681248,1.9094372e-05,0.009370711,-0.019208923,0.019617345,0.036553428,0.009661842,-0.0095838215,0.00949863,0.05621024,-0.0012343195,-0.10692451,0.03604914,-0.005090564,0.0016862417,0.091894604,-0.004927909,-0.025929086,-0.078148164,-0.010329854,0.0043074666,0.04089597,0.012131667,0.012199398,-0.020629821,0.0118408995,0.0129535375,0.024141293,0.054144684,-0.028935129,0.052407075,0.053436834,0.03151015,-0.02913968,0.02248868,0.036315598,0.010819087,-0.0030657891,0.018937662,-3.83113e-05,0.018541912,-0.022791563,-0.046304014,-0.04271194,-0.024255281,0.0040089395,-0.000107437096,-0.023781613,-0.007816305,0.019084493,0.011128599,0.07513534,0.048134036,0.04298125,-0.0066044284,0.03616531,0.020310573,0.02791434,-0.05174191,-0.010179802,0.039310914,0.023950087,-0.0028884867,0.08436258,0.006016662,0.024641354,0.05440621,0.03314823,-0.015292214,-0.049835317,0.014906329,-0.007433095,0.023168776,-0.034556013,-0.07381936,0.010536344,-0.0010438391,-0.0147009585,0.026222883,-0.026152914,0.060245108,-0.049573172,-0.018209208,-0.014328683,0.0052110804,-0.019277807,0.0041846028,-0.079332255,-0.013760327,0.00914954,-5.901147e-33,-0.005977292,0.025688512,0.024628758,0.01127461,-0.09909692,-0.048910175,0.030675586,0.0024513605,-0.051710352,-0.01435038,-0.04504234,-0.0015586053,0.0243258,0.0023048688,-0.036693208,-0.072892815,0.011179813,0.00057596783,-0.0059879194,-0.033928953,-0.058084667,0.003109337,0.030196283,0.04242983,-0.009863396,0.02855958,-0.012060397,0.043087106,-0.020088287,-0.007901708,0.021487795,0.0038966904,-0.0032375236,0.022722613,0.017828377,0.06614204,-0.0268959,-0.005683358,-0.05187458,0.0445424,0.0049306946,-0.002091811,0.014366786,0.011442393,-0.058383714,0.025108762,-0.004097464,-0.010817041,-0.027824713,0.06845582,-0.0034994688,-0.032779034,-0.0558935,0.018225303,-0.014046906,-0.035931624,0.0063414145,-0.024590766,-0.12389801,0.0018188272,-0.021222599,-0.05891324,0.009753007,0.0014737148,-0.007956008,-0.0129774995,0.100158446,0.07372675,-0.06758517,0.035971273,-0.0010348761,0.043814667,0.032206036,-0.037416473,-0.037972555,0.013164626,-0.05665367,0.004639191,-0.0036573869,-0.027476218,0.0039969003,-0.012673019,-0.024415681,-0.0282261,-0.037032507,-0.13491747,-0.0021194406,-0.0035709853,-0.010654203,-0.01904675,-0.0051431684,0.09320847,-0.00583542,-0.021843227,0.02911638,-0.048310786,-0.0175626,-0.036012724,-0.0077827764,0.00785681,0.017249307,0.020966258,-0.04058929,0.083967194,0.01879495,0.030622719,0.0029683346,-0.0005876084,-0.011321756,0.0043854862,-0.006029812,0.0028517798,0.06280698,-0.013869605,0.018940158,-0.028290382,0.014277855,0.042901896,0.038092278,0.01738529,0.017803619,-0.0076578343,-0.03354011,0.0085039865,-0.054666404,-0.0117449,-0.03330161,0.034405723,0.06396666,-0.0012429849,0.031971306,-0.07092625,2.3090725e-07,-0.020735241,-0.026453694,0.0170531,-0.07928664,-0.0030725452,-0.038539413,0.02412167,0.051226586,-0.031468425,-0.0143749,-0.0010443905,0.026046159,-0.0040855273,-0.0061072563,-0.026905581,-0.024701215,-0.080022365,0.014567439,-0.0388092,-0.008688583,0.020936565,0.035755794,0.02394574,-0.02812886,0.0039120107,0.005751944,0.026169987,-0.021407148,-0.06726731,-0.02422734,0.06890272,-0.018708693,0.013227421,-0.0027762016,0.04088113,-0.05506917,-0.008941695,0.019927254,0.024943398,0.022985263,-0.010358985,-0.034463715,-0.031446572,0.040268682,0.048379045,-0.062699765,-0.08451923,0.05457744,-0.011880986,0.023146829,-0.00011583058,0.004569894,0.014491031,0.023752946,0.008141938,-0.025499748,-0.019746229,0.040897388,-0.041801214,-0.04674807,0.013942224,-0.08361571,-0.0001683599,0.0044444758,0.037752267,0.060519654,0.017886663,1.9830872e-34,-0.014023646,0.038741086,-0.017871125,0.0063545206,-0.017818503,-0.0276379,0.06109331,0.01768834,-0.028200477,-0.014363872,0.015258903]', '[0.033837046,-0.06803316,-0.018025797,-0.0056481073,-0.029693358,-0.019627247,-0.006204474,0.031447515,0.077017285,-0.004237914,0.040770747,0.04100224,0.024334213,0.0361331,0.004951901,-0.059648197,0.009685677,0.015713451,-0.055363007,-0.027368378,-0.0004996693,0.012405203,-0.03676662,0.03168906,0.090265766,-0.014682238,0.008998706,-0.02011755,0.06336816,-0.03725998,0.04199386,-0.03665474,0.030018536,0.03082198,1.94926e-06,-0.0018095177,-0.003524029,-0.0100777615,-0.0060323733,0.049866434,-0.016250484,-0.05167278,-0.034334294,-0.059994657,0.02417369,-0.08037153,-0.015045397,0.0023516768,-3.5253146e-05,0.040514283,0.013368556,-0.02344921,0.01596506,0.025934797,-0.05988698,-0.049065277,0.012674649,0.07983612,0.021850064,0.034757596,-0.030174559,0.02866464,-0.0030473291,0.001964781,0.0024576804,0.024056064,-0.023221092,-0.036972154,0.025555532,0.03982894,0.044799924,-0.027190493,0.041778043,0.030474124,-0.03568494,-0.04916689,-0.022674814,-0.019485721,-0.023557909,-0.00018997063,0.00054309866,0.05514168,-0.045289397,0.032322,0.041855525,0.02163572,0.01775198,-0.005536577,0.0072144424,-0.006493389,-0.0037079495,-0.04261907,0.01949386,0.04332436,-0.03909813,-0.0120884245,0.020391079,-0.06971459,0.042590994,-0.046520323,-0.05960735,-0.0037468188,-0.024378834,0.010102658,-0.0065374384,-0.009760189,-0.0003879492,-0.0071796556,-0.008715517,0.012310433,0.00207937,-0.026603729,-0.028411957,0.008116364,-0.04809951,0.029793927,-0.023822151,0.022684475,0.05631468,0.013568248,-0.0118737575,-0.008246304,-0.0022935949,-0.020965282,-0.030203672,-0.0026090492,-0.04829175,0.02454712,-0.016093401,0.06423674,0.05094298,0.030895863,-0.015272119,-0.02190589,-0.009119519,0.030337106,-0.023963839,0.0024464126,0.011839453,0.0023153157,0.0019635565,-0.058104455,-0.01690495,0.027377179,-0.035079498,-0.0019217049,-0.047470782,0.02612778,-0.03704667,0.018211782,-0.024535501,0.012975554,-0.06107177,0.018808559,0.06742816,0.017233483,0.0472232,-0.054833636,-0.055504527,0.018980687,-0.012381481,-0.0009910121,0.007801334,0.0049375254,-0.016590789,-0.036058914,-0.036121674,0.09841977,-0.05401656,-0.066740826,-0.024151977,0.028308768,-0.01780215,0.0689768,0.018131364,0.040068336,0.0624756,0.015504363,-0.05892749,0.045463175,0.06066398,-0.10400596,0.05498762,-0.003533287,0.12086076,0.058713492,0.0152831515,0.0051184664,0.038287915,0.007813171,0.024669647,0.03670615,-0.09206905,0.028473109,0.0059630037,-0.008554585,-0.032716434,-0.012786363,0.044842176,0.0266525,0.05304138,-0.038752798,0.05947639,-0.015775558,-0.008711839,0.029656565,0.04477324,-0.026642023,-0.012879998,-0.04102538,0.03764214,0.0028041943,-0.052939057,-0.014783922,0.012151917,0.048747037,0.0040956596,0.0032598895,-0.055204026,0.06686841,-0.011276149,-0.04155945,0.065130316,-0.042811908,0.04066478,0.024539206,-0.06758828,0.003720745,-0.035698127,0.04452307,-0.0060865865,0.009060286,0.02862772,0.0046320497,0.012996271,-0.007760905,0.07137674,-0.04264403,0.012412816,-0.03746362,-0.009253131,0.09209732,0.03681653,-0.007495955,0.075728066,-0.022150999,-0.028991442,0.023623925,-0.023191579,-0.03186429,-0.0012045625,-0.0258087,0.046157,0.0022283366,0.0029390473,-0.030067282,-0.014490827,0.031475138,-0.02654779,0.041997097,0.026949354,-0.027207647,0.003091587,0.019113075,0.06188158,-0.029626569,0.016559402,0.032732915,3.8258055e-05,-0.014715277,0.00480888,0.025395889,0.018478906,-0.0052954024,-0.01850264,-0.012157651,0.013323434,0.03678491,-0.011013859,-0.019837804,0.014552337,-0.008465773,-0.019755427,-0.02596653,-0.00022892469,-0.011342059,-0.007408235,-0.08008994,-0.012537533,0.020918667,-0.0836502,-0.027534036,-0.029022526,-0.038447026,0.016687227,0.04443253,0.02201481,-0.004635942,-0.0030994008,0.0287439,0.00021875014,-0.046563808,-0.021273049,0.0003164973,0.002499911,-0.006604344,0.0013489422,0.031519707,-0.000117208445,-0.049840655,0.025887776,0.010341336,-0.0256416,-0.08277572,-0.0067328135,0.040778827,-0.009754246,-0.040359084,-0.01050714,0.09818345,-0.0040605096,0.019535352,-0.0065294732,0.042889826,-0.019097148,-0.0074848696,-0.021105507,-0.026291417,0.038944587,-0.046436653,0.018067557,-0.03654926,-0.033122506,0.033661887,-0.07831243,-0.016194183,-0.028233705,-0.017864546,0.03507192,0.024888499,-0.06497615,-0.020875286,-0.01858089,0.011414388,-0.003422162,-0.0118071595,-0.025703566,0.034672353,0.027023917,-0.035483535,-0.0301028,-0.03824805,-0.021866309,0.038455695,-0.042086206,0.026488949,0.038287524,-0.03679385,-0.026316745,0.06281874,0.012592511,-0.02169019,-0.040871132,-0.0074524633,0.08165846,0.06299594,0.01655833,0.039561715,-0.017193832,-0.035091862,0.09069092,0.01709637,0.004157385,0.032227002,-0.017537847,-0.0065977224,0.031820253,-0.0048281313,-0.022698922,0.028288329,0.03942058,-0.030320326,0.06804257,-0.02431245,0.008659249,-0.0412072,-0.019603163,-0.020590648,-0.031121057,0.0111162085,0.028869571,-0.035538364,-0.067694195,0.020319482,-0.010325282,-0.042860303,0.018889127,0.019794287,0.026907586,0.041463695,0.06438433,0.03900172,-0.0013052035,0.03801582,-0.009500974,0.039974153,0.017651152,0.03233446,0.028554061,-0.13630153,-0.012580845,-0.0013868903,-0.016930956,0.036086597,0.011874502,0.018792354,-0.0343115,-0.06591038,0.04941262,0.005903084,0.013164039,0.012480084,-0.0003335899,0.048676237,-0.0043379543,0.055252116,0.038868938,0.03447401,-0.05413626,-0.015851576,0.041191198,-0.015267767,-0.036443066,-0.015220416,0.036402147,-0.066363476,0.001436758,0.01910526,-0.026393443,0.016952192,-0.044673797,0.033180755,0.0640847,-0.019060636,0.02774771,-0.08188762,0.0057099136,0.030018844,-0.024589801,0.0034150712,0.0076797237,-0.026382456,0.05789575,-0.0021711779,-0.0047719963,-0.024110425,-0.0886689,-0.028934179,-0.06034141,0.038642548,0.025990104,0.031560767,0.01851324,0.02741307,-0.013641012,0.015999567,-0.023090944,-0.024900712,-0.0075928955,0.0035906576,0.024770427,0.022562638,0.012596381,0.035985615,0.015944753,0.010095286,-0.041935313,0.023376022,0.033878688,0.015118812,0.02714513,0.07419139,-0.03333047,-0.1011299,0.009360035,-0.024747327,0.054644074,-0.00070869643,0.011920449,-0.03146132,0.037576657,-0.00038484854,-0.01106277,0.09745955,0.014739724,0.051652413,-0.0057517155,0.02207475,0.017570423,0.082059614,0.06655412,0.018734312,-0.041722864,0.04074694,-0.02875557,0.041947413,-0.027658822,-0.08478,-0.0016170853,-0.052907456,0.017364053,-0.02127154,0.03630493,-0.018431079,0.07802275,-0.04084988,0.06791757,-0.018740261,0.0022623695,-0.0061600497,0.035865616,0.015086478,0.01881286,-0.048862044,-0.019437663,0.014666146,-0.0057128635,-0.01086996,0.07697345,-0.028903084,-0.009558135,0.0039992207,-0.009492698,-0.028981881,-0.024252241,0.08267477,0.007900661,0.024716778,-0.016282178,0.05746392,-0.011582789,-0.06863124,-0.07180141,0.00396302,-0.009418362,0.022392139,-0.01308323,-0.03252353,0.039807364,-0.0014651841,-0.03685513,0.03960055,-0.04279245,0.014164923,-0.034767054,-6.423112e-33,0.022119028,-0.011200386,0.036637213,-0.052313603,-0.12232478,-0.06050153,0.02203606,0.005415488,-0.06319496,-0.004166385,-0.04166712,-0.02051162,0.0038294005,0.0014455691,-0.009106579,-0.041284073,-0.029734883,-0.0030509683,0.024586078,-0.09148982,-0.028508842,-0.026624136,0.069632776,0.03836989,0.00945121,-0.015326424,0.01662708,-0.018373793,0.026237467,-0.015035378,0.004873889,-3.3526445e-05,-0.0006786401,0.008304162,0.014851762,0.024643734,-0.04298832,0.024233244,-0.004910592,0.06015998,0.00010436686,0.03701769,0.004402206,0.01407824,-0.010752702,0.0188796,-0.02525059,-0.0064191013,-0.032301653,0.07507152,-0.00035235807,-0.003943975,-0.035161823,-0.007633619,0.021882495,0.033588946,0.005945764,-0.036320806,-0.039868534,-0.02713765,0.057281204,-0.0169856,0.0038867602,-0.027795503,-0.02021086,0.011719046,-0.05065195,0.012463279,-0.006427746,-0.0065211416,-0.029574364,0.0013924588,-0.04423411,-0.051062062,-0.100262105,-0.054818913,-0.07325419,-0.022694428,0.014272789,-0.024925986,-0.042995904,0.02281749,0.005679609,-0.008441516,-0.0013502033,-0.068279184,-0.009263651,-0.0013764151,-0.013420432,-0.03412165,0.0038140048,0.0041853436,-0.009823822,-0.018772993,0.032598495,-0.07454059,-0.02169596,-0.016482573,0.008740391,0.026918065,0.0050365473,0.027864667,-0.06456008,0.080255166,-0.025598725,0.0535235,-0.0073539917,-0.030940557,-0.017066292,0.009329174,0.011193288,0.012739698,0.06292494,-0.0061307885,0.008019152,-0.008644537,0.00090960134,0.006210709,-0.0041688555,-0.08082066,0.07850445,-0.0030805692,0.024814174,0.013608678,-0.036032066,0.017994745,-0.05153367,0.05502157,0.041927326,0.023027644,0.05460262,-0.043665618,2.713014e-07,-0.032992356,0.052206457,-0.017315134,0.0036382894,-0.025536446,-0.010073741,0.0073018437,0.048272535,-0.02797344,0.018791948,-0.01934682,-0.024037823,-0.01154214,-0.008383137,-0.060072437,-0.047844704,-0.05497573,-0.023472738,-0.0062257983,-0.024672283,0.063099176,-0.009041084,-0.002714515,-0.01533521,0.0016218545,-0.00891405,0.020146985,0.027499804,0.0035070942,-0.045669284,0.040630896,-0.06288449,0.012168586,0.02027213,0.018061547,-0.03815768,0.03441936,-0.0033469119,0.04217981,0.044961028,0.008450091,-0.07096843,-0.03574776,-0.03234475,0.06599975,0.0144727845,-0.04707047,0.025024427,-0.0037968538,0.0014846752,-0.023093976,-0.012176627,0.017155746,-0.0029917597,-0.022806631,0.025624178,0.043273713,0.0040410347,-0.03473362,0.0572647,0.0017274432,-0.041365873,0.015578259,0.034882993,0.0198656,0.042711258,-0.025295654,2.1661463e-34,-0.031201376,0.043052506,-0.008908374,-0.055762824,-0.008283254,-0.01717487,0.036810823,-0.0068219034,0.039375417,-0.023278698,-0.024452945]']

In [13]:
from pathlib import Path

DOCUMENTS_PATH = Path('documents')

def utc_now():
    return datetime.now(timezone.utc)

def load_sql_paths(directory: str) -> list[Path]:
    documents_path = Path(DOCUMENTS_PATH) / directory
    return list(documents_path.glob("*.sql"))

print(load_sql_paths("anforanden"))

[PosixPath('documents/anforanden/anforande-202223.sql'), PosixPath('documents/anforanden/anforande-202324.sql'), PosixPath('documents/anforanden/anforande-202425.sql'), PosixPath('documents/anforanden/anforande-202526.sql')]

In [ ]:
import re

sql_path = Path("documents/anforanden/anforande-202223.sql")
with sess.begin():
            for path in load_sql_paths(sql_path):
                print(f"Processing: {path.name}")
                raw_sql = path.read_text(encoding="utf-8")
                inserts = re.findall(r'INSERT INTO .+?;', raw_sql, re.DOTALL)

                for insert in inserts:
                    sess.execute(text(insert))

In [18]:
sql_path = Path("documents/anforanden/anforande-202223.sql")

raw_sql = sql_path.read_text(encoding="utf-8")
inserts = re.findall(r'INSERT INTO .+?;', raw_sql, re.DOTALL)

print(inserts[2])

INSERT INTO anforande (dok_hangar_id,dok_id,dok_titel,dok_rm,dok_nummer,dok_datum,avsnittsrubrik,underrubrik,kammaraktivitet,anforande_id,anforande_nummer,talare,parti,anforandetext,intressent_id,rel_dok_id,replik,systemdatum)
    VALUES (5147373,'HA091','Protokoll 2022/23:1 Måndagen den 26 september','2022/23',1,'2022-09-26 00:00:00','Val av förste vice talman','','','f0d46b26-e94e-ed11-9177-901b0eac4c70',11,'Annie Lööf (C)','C','<p>Fru ålderspresident och ärade ledamöter av Sveriges riksdag! Centerpartiet har stort förtroende för Kenneth G Forslund som riksdagens förste vice talman, och vi står bakom förslaget. Vi tycker att det är rimligt att riksdagens största parti innehar vice talmansposten och kommer därför att aktivt rösta ja till Kenneth G Forslund som förste vice talman. Vi hoppas på ett lika brett stöd här i kammaren som vid valet av talman - det vore för Sveriges bästa.</p><p>Överläggningen var härmed avslutad.</p><p>Kammaren valde med acklamation <em>Kenneth G Forslund</em><em> </em>(S) till förste vice talman.</p><p>(Applåder)</p>','0862868280923','','N','2022-10-18 15:31:55');

In [11]:
from sqlalchemy import text

pingas = ["pingas", "mingas", "chingas"]

table = "anforande"

col = ", ".join(f'"{ping}"' for ping in pingas)

t = text(f"SELECT {col} from {table}")

print(t)

SELECT "pingas", "mingas", "chingas" from anforande

In [2]:
from sqlalchemy import create_engine, text
from sqlalchemy.orm import sessionmaker
from langchain_huggingface import HuggingFaceEmbeddings
import torch

DATABASE_URL = "postgresql+psycopg2://gov_check_user:gov_check_pw@localhost:5432/gov_check_db"

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-mpnet-base-v2",
    model_kwargs={"device": device},
    encode_kwargs={"batch_size": 128, "normalize_embeddings": True},
)

engine = create_engine(DATABASE_URL)
SessionLocal = sessionmaker(bind=engine)

query = "Vad har Magdalena Andersson sagt gällande sammarbete med Sverigedemokraterna (sd)?"
query_embedding = embeddings.embed_query(query)

with SessionLocal() as sess:
    result = sess.execute(text("""
        SELECT talare, parti, anforandetext FROM anforande ORDER BY embedding <-> CAST(:embedding AS vector) LIMIT 20
    """), {"embedding": str(query_embedding)}).fetchall()

    for row in result:
        print(f"{row.talare}")
        print(f"{row.anforandetext[:1000]}")
        print()

Jan Riise (MP)
<p>Fru talman! Jag kan inte svara för Magdalena Andersson. Det är väl det kortfattade svaret på den frågan. Vi har pratat om detta vid flera tillfällen under denna debatt. Det är inte vi som är Socialdemokratiska arbetarepartiet. Varken Vänsterpartiet eller Miljöpartiet har några som helst möjligheter att ta ställning i den frågan. Lena Hallengren har på ett utmärkt sätt redovisat vad man tänker sig att göra och inte göra. Jag har inga ytterligare kommentarer till det.</p>

Lena Hallengren (S)
<p>Herr talman! På lördag återuppstår den högerextrema Salemmarschen i en av Stockholms kranskommuner. Terrorklassade Nordiska motståndsrörelsen ska marschera samtidigt som det arrangeras en julmarknad.</p><p>Magdalena Andersson har tydligt markerat mot våldet och mot detta sätt att sprida oro och rädsla, och Socialdemokraterna vill förbjuda våldsbejakande aktivklubbar. Jag kände inte till att det också är regeringens uppfattning, så då väntar vi på ett sådant förslag.</p><p>Från statsministern hörs det dock för lite när det gäller att ta avstånd från denna avskyvärda företeelse. Jag saknar en regering som sätter gränser, som tydligt markerar mot högerextremism och oprovocerat våld, som manar till sammanhållning, som står upp för alla människors lika värde och som i förlängningen står upp för svensk demokrati.</p><p>(Applåder)</p>

Annie Lööf (C)
<p>Herr talman! Jag vill tacka Magdalena Andersson för det förtroendefulla samarbete som vi har haft under hennes tid som partiledare men också tacka för det fina samarbete som jag hade förmånen att ha med Stefan Löfven. Jag har också haft förmånen att samarbeta med Håkan Juholt under hans tid som partiledare, men då var det mer debatt än samarbete.</p><p>Jag vill också tacka Magdalena för hennes ansvarstagande i en för Sverige orolig tid och för modet att ompröva gamla sanningar för Sveriges säkerhet. Jag har alltid uppskattat hennes raka sätt och starka integritet och att hon har tagit sig tid att träffas, sitta ned med ganska många koppar kaffe och hitta vägar framåt när det gäller både budgetfrågor, statsministeromröstningar och Nato.</p><p>Jag är väldigt stolt över vårt samarbete i januariavtalet och över att jag fick medverka till och gratulera Magdalena Andersson som första kvinna som statsminister. För någon vecka sedan stod ett antal sjuåringar i denna talarstol, och de kunde

Arbetsmarknads- och integrationsministern Johan Pehrson (L)
<p>Fru talman! Liberalerna drar samma slutsats som före sommaren då vi hade exakt samma debatt. Magdalena Andersson må ha vissa förtjänster. Magdalena Andersson har en förmåga att till och från fatta svåra beslut. Men Magdalena Andersson sitter i ett grönrött vänsterkärr där man sjunker ned djupare och djupare och inte kan ta tag i de stora samhällsproblem som har skapats i Sverige och som vi nu har ärvt. Det handlar om en fungerande energipolitik för företag, människor och klimat. Det handlar om att se till att vi har en skola som fokuserar på kunskap och där man sätter in insatser tidigt. Det handlar om att på riktigt gör något åt friskolornas framtid. Det handlar om att bekämpa brottslighet och att ha en migration som fungerar med en integration. På alla dessa områden står Magdalena Andersson svarslös och är ansvarig för åtta år. Vi borde ha gjort det bättre när vi jobbade ihop.</p>

Energi- och näringsministern Ebba Busch (KD)
<p>Fru talman! Jag som energiminister för samtal med flera framträdande nuvarande och före detta socialdemokrater. De är konstruktiva och kunniga. Det handlar om många svåra avvägningar. Där lägger vi grunden för en hållbar energipolitik som inte sätter partipolitiska låsningar utan Sveriges bästa i centrum. Dem fortsätter jag gärna. De pågick efter sommaren, före jul och fortsätter även nästa vecka.</p><p>Jag har två frågor. Önskar Magdalena Andersson sitta ned och samtala med mig? Det gör jag mycket gärna. Och kommer Daniel Helldéns veto när det gäller kärnkraft och att stötta en socialdemokratisk regering vid ett potentiellt maktskifte att vara det som Magdalena Andersson navigerar utifrån?</p>

Jimmie Åkesson (SD)
<p>Herr talman! För att citera Magdalena Andersson själv: Var det där ett ja eller ett nej?</p><p>Frågan om karensen får Magdalena Andersson jättegärna ställa till mig när det är hennes tur att replikera på det jag säger. Men nu ställde jag en väldigt konkret fråga, och jag är egentligen inte särskilt intresserad av Socialdemokraternas egna förslag, som de har hittat på i opposition, om Sverigebränsle och vad det nu är för olika konstruktioner de hittar på. Det jag är intresserad av är hur de ska navigera i den politiska verkligheten när de ska bygga sin regering, som de vill bilda, på andra partier som vill höja bränslepriserna i Sverige.</p><p>Kan Magdalena Andersson lova att de, även om det blir en socialdemokratiskt ledd regering efter nästa val, ändå kommer att garantera fortsatt låga bränslepriser, naturligtvis inte beroende på världsmarknadspriset utan beroende på reduktionsplikt, skatter och annat? Det är ingen svår fråga att svara ja eller nej på.</p><p>(Applåder)</p>

Utbildnings- och integrationsministern Simona Mohamsson (L)
<p>Herr talman! Magdalena Andersson vill aldrig ta ansvar för sitt parti.</p><p>Liberalerna och regeringen har miljardsatsat för att korta köerna och dubblerat stödet till just ätstörningsvården, men det är Magdalena Anderssons parti som styr i Region Stockholm. Det är Magdalena Anderssons parti i Stockholm som har lagt ned ätstörningskliniker. Det är Magdalena Anderssons parti som har slussat runt patienter som hockeypuckar, utan vård. Det är vad barnen här i Stockholm vittnar om.</p><p>Min fråga är fortsatt enkel: Är det här vad en ung tjej eller kille som behöver få hjälp hela tiden i sin vardag kan förvänta sig i resten av landet om det mot all förmodan blir ett maktskifte i höst?</p><p>(Applåder)</p>

Jimmie Åkesson (SD)
<p>Fru talman! Magdalena Andersson har rätt i att det inte bara är Socialdemokraternas fel. Alla regeringar i det här landet de senaste 30 åren, eller till och med längre tillbaka än så, har ansvar för haveriet. Men nu är det Magdalena Andersson som står talarstolen och som jag replikerar på, och då är det rimligen också hon som ska svara på de frågor jag ställer.</p><p>Magdalena Andersson kan vara helt förvissad om att jag lyfter dessa saker också med mina "kompisar", med andra partier och inte minst med regeringen. Skillnaden mellan Magdalena Andersson och exempelvis statsministern är att statsministern offentligt har tagit avstånd från den tidigare politiken och till och med bett svenska folket om ursäkt för de misstag han begått. Det Magdalena Andersson nu gör är precis det motsatta. Hon tar inte ansvar för någonting. Hon skyller på alla andra. Hon skyller till och med på mig för att Sverige har genomlevt detta invandringshaveri. Det är totalt skamlöst, fru talman.</p><p> STYLEREF

Boriana Åberg (M)
<p>Herr talman! Jag tackar Sofie Eriksson för den mycket emotionella frågan.</p><p>Det som Sofie Eriksson benämner bröstklang var vårt vallöfte, det vill säga att få bukt med all kriminalitet - särskilt den som har sin grund i felaktig folkbokföring. Det är inget löfte som vi har backat från. Tvärtom! Vi tänker genomföra alla våra vallöften.</p><p>Sedan var det en fråga om att vi har underkänt den socialdemokratiska politiken på området. Ja, det har vi gjort. Den som minns kommer ihåg när Magdalena Andersson gav direktiv om samordningsnummer. Då var hennes direktiv hur man ännu lättare skulle tilldela samordningsnummer till människor som inte kan folkbokföras i Sverige. Det är bland annat mitt parti som har uppmärksammat att samordningsnummer tilldelas lättvindigt; det räcker att köpa en begagnad bil och skicka en dålig kopia på sitt körkort från utlandet så får man ett samordningsnummer i Sverige. Det finns skäl att vara självkritisk när man ser att vi har underkänt en felaktig politi

Jimmie Åkesson (SD)
<p>Herr talman! Det är naturligtvis bara en ren slump att det här händer nu när vi har en ny regering på plats och inte när Magdalena Andersson var statsminister - självklart!</p><p>Socialdemokraterna trixar och fixar retoriskt, men när det väl kommer till kritan är man inte med. Man mäktar inte med att fatta de beslut som behöver fattas. Ett exempel är gängkriminellas medborgarskap. Man mäktar inte med att göra det som krävs.</p><p>Herr talman! Varför är det så viktigt för Socialdemokraterna och för Magdalena Andersson att gängledare med dubbla medborgarskap ska få behålla sina svenska pass? I min värld är det helt obegripligt att Socialdemokraterna kan tycka att det är så viktigt. Jag tycker att Magdalena Andersson måste svara på varför det är så viktigt att gängledare får behålla sina svenska pass.</p><p>(Applåder)</p><p> STYLEREF Kantrubrik \* MERGEFORMAT Partiledardebatt</p><p>I detta anförande instämde Robert Stenkvist (SD).</p>

Energi- och näringsministern Ebba Busch (KD)
<p>Herr talman! Magdalena Andersson är välkommen att återkomma i nästa replikskifte, där rollerna är omvända, med fler frågor.</p><p>Ett raljant tonläge, rätt använt, kan tydliggöra åsiktsskillnader. Det kan vara elegant. Det kan vara roligt. Jag har uppskattat när mina meningsmotståndare ibland till och med har häcklat min politik eller mitt sätt att agera i politiska sammanhang, när det skett med lite finess. I andra sammanhang kan ett raljant tonläge användas för att dölja osäkerhet. Att använda Putins invasionskrig på det här sättet tycker jag är osnyggt.</p><p>Min fråga var väldigt enkel. Kan vi söka samarbete och breda överenskommelser för Sveriges bästa, där vi också kan påverka omvärlden positivt, kring ny kärnkraft i Sverige? Är svaret ja, eller är det nej?</p>

Statsministern Ulf Kristersson (M)
<p>Herr talman! När vi besökte militärövningen i Norge i mars förra året sa Magdalena Andersson, som då var statsminister, någonting viktigt: Vi kan vara oeniga om många saker, men vi kämpar båda för Sveriges trygghet. </p><p>Vi <em>är</em> oeniga om mycket - Magdalena Andersson är socialdemokrat, och jag är moderat. Jag har respekt för våra olikheter och våra olika roller. Men budskapet var viktigt, nämligen att vi sätter Sverige främst. Jag prövar därför igen. Är Socialdemokraterna beredda att bidra med tydliga besked om stöd till reformer som gör att även kärnkraften kan bidra till en fördubblad energiproduktion? Är Socialdemokraterna beredda att bidra till långsiktiga spelregler och tydliga investeringsförutsättningar för alla som vill bygga ny energi i Sverige? </p><p>Är man beredd att inte ställa kraftslag mot kraftslag utan inkludera ny svensk kärnkraft i en långsiktig svensk energipolitik? Är svaret ja eller nej?</p>

Saila Quicklund (M)
<p>Fru talman! Jag tackar Johanna Haraldsson för frågan. </p><p>Ja, Johanna Haraldsson – varför står vi här? Vi hade åtta år med en socialdemokratiskt styrd regering, som inte införde detta. Jag uppfattar det som att det här var ett stort önskemål från Johanna Haraldsson och Socialdemokraterna. Jag kan lägga det som slutfråga: Drev Socialdemokraterna eller Johanna Haraldsson det här? Det verkar nämligen vara angeläget. </p><p>Vi vet att arbetsgivaren har det absolut största ansvaret för arbetsmiljöfrågorna på en arbetsplats, men jag ser det också som ett kollektivt ansvar. Arbetsgivarparterna bär ett stort ansvar, men det gör även skyddsombuden. </p><p>När det gäller sanktioner ser regeringen nu över straffreformer. Även brottsbalken, som arbetsmiljöbrott faller in under, ser man över. Sanktioner diskuteras. I motsats till vad ledamoten sa i det förra replikskiftet om att vi inte kommer att presentera en arbetsmiljöstrategi kan jag meddela att det arbetet pågår och att den kommer att p

Jimmie Åkesson (SD)
<p>Herr talman! Antingen hörde Magdalena Andersson ett svar eller så gjorde hon det inte. Uppenbarligen gjorde hon det inte. Mitt svar var att det blir väldigt svårt att få igenom sina förslag här om man inte är beredd att förhandla med framför allt stora partier i den här kammaren. Säger man att man konsekvent inte tänker göra det – man tänker inte samarbeta, och man tänker inte ens prata eller förhandla – får man inte igenom sina förslag. Jag tänker inte stå här och förhandla med Magdalena Andersson; det säger sig självt.</p><p>Det stämmer att vi har mycket att städa upp. Så är det, och det visste vi när vi sökte folkets mandat för att göra just detta: städa upp efter Magdalena Andersson. Vi städar upp efter tvåsiffrig inflation, misslyckade mål om Europas lägsta arbetslöshet, drivmedelspriser på uppåt 30 kronor, kärnkraft som lades ned och en historiskt omfattande asylinvandring med allt vad det innebär i form av kriminalitet, utanförskap och allmän splittring i det svenska samhälle

Jimmie Åkesson (SD)
<p>Herr talman! Nu har vi haft diskussioner om antisemitism och annat med inte minst Magdalena Andersson. Där är även Vänsterpartiet berört - milt uttryckt. Det är klart att jag kan ställa frågor till Nooshi Dadgostar om det, men jag bryr mig inte om det; det kan vi göra i andra sammanhang.</p><p>Däremot tänkte jag fråga vilken ministerpost Nooshi Dadgostar tänker ha i Magdalena Anderssons regering. Vilka övriga portföljer tänker Vänsterpartiet lägga beslag på?</p>

Energi- och näringsministern Ebba Busch (KD)
<p>Herr talman! Jag kunde inte hålla med mer om det sista som Magdalena Andersson sa. </p><p>Faktum kvarstår dock att mycket mer hade kunnat göras under åtta år med S vid makten. Under er regeringstid skedde faktiskt en avindustrialisering av Sverige, Magdalena Andersson. Nu sker i stället en nystart. Sverige tar på sig ledartröjan i den gröna omställningen, där industrin kommer att spela en avgörande roll. Den nya strategin för norra Sverige kommer också att bli en viktig kugge i det arbetet, och då behöver det helt enkelt bli lättare att öppna nya gruvor. </p><p>Detta kräver en översyn av lagstiftning, tillståndsprocesser och handläggningstider, och det kräver också politisk stabilitet över tid. Socialdemokraterna behöver visa ledarskap även när vindarna blåser åt andra hållet och inte dra saker i långbänk. Min fråga är därför om Magdalena Andersson kan tänka sig att byta ut MP mot KD - "KDS" har ju varit ett framgångsrikt koncept förut! </p><p>Allvarligt talat: Ska jag tolka Magdale

Utbildningsministern Johan Pehrson (L)
<p>Herr talman! För jättemånga år sedan avfärdade Magdalena Anderssons företrädare Tage Erlander det svenska medlemskapet i EG, eller EU som det heter i dag, som något som inte fungerade med vår neutralitet eller vår ekonomi. Detta har ändrat sig, vilket jag är väldigt glad för. Sverige hör hemma i centrum av Europa.</p><p>Ibland brukar jag fråga Magdalena Andersson om det inte är så att beslut ska fattas när det är relativt mycket lugn och ro. Jag tänker på frågan om euromedlemskap. Om Sverige ska vara en trygg hamn i ett tryggt Europa, som Magdalena Andersson hänvisade till i sitt huvudanförande, och om vi ska stärka den svenska positionen på den inre marknaden, blir vi då inte starkare med ett svenskt medlemskap i eurosamarbetet än med bara den svenska kronan?</p>

Ilona Szatmári Waldau (V)
<p>Fru talman! Jag hörde faktiskt inget svar på min fråga. Min fråga gällde om KD och Cecilia Engström verkligen tror att kommuner höjer skatten för att slösa med skattemedel och att rätt lösning är att sänka deras statsbidrag. Är det verkligen lösningen? De med låga inkomster är ju de som drabbas ännu mer om kommuner inte har resurser för att klara skolan, vården och omsorgen.</p>

Pontus Andersson Garpvall (SD)
<p>Herr talman! Tack så mycket, Lars Isacsson, för svaret!</p><p>Som jag ser det är problemet med socialdemokrater att de säger en sak nu, men sedan ska de kompromissa och försöka samarbeta med de andra på vänstersidan i politiken.</p><p>Inom andra politikområden försöker Socialdemokraterna framställa det som att de alltid har varit för kärnkraft, exempelvis. Men sedan regerar de med Miljöpartiet och stänger ned kärnkraften. De påstår också att de alltid har varit för en kontrollerad invandring. Men sedan styr de ihop med Miljöpartiet och Vänsterpartiet och lämnar dörren till Sverige på glänt. De säger att de vill beskatta de rika, men senast valde de att styra ihop med Centerpartiet och avskaffade värnskatten för de allra rikaste så att dåvarande finansminister Magdalena Andersson hade råd med ytterligare en dyr skidsemester i fjällen.</p><p></p><p>Hur ska väljarna kunna lita på Socialdemokraterna? Kommer de att kunna hålla det de lovar när de har haft svårt för att hålla det de har l

Statsministern Ulf Kristersson (M)
<p>Herr talman! Magdalena Anderssons intresse för statsskulden dök upp den dag hon inte längre var finansminister. Tidigare hade man en högre statsskuld än den vi har i dag. ”Vi har Europas bästa offentliga finanser” lät det på den tiden. Men de offentliga finanserna är bättre i dag än vad hon lämnade efter sig för fyra år sedan.</p><p>Socialdemokraterna tror att man kan höja skatter utan att någon ska märka det och utan att det får några konsekvenser. De tror att man kan införa en bolåneskatt på bankerna som bara ska försvinna, som ingen ska se och som ingen ska märka. Men sådana skatter kommer att leda till ökade bolånekostnader.</p><p>Vänsterpartiet tror att man kan införa en fastighetsskatt som bara ska drabba några få personer. Andra ska inte märka någonting.</p><p>Det där är inte sant. De duckar frågan om skattehöjningar för svenska folket. De vägrar att berätta konsekvenserna för helt vanliga barnfamiljer. Vi kommer att avslöja dem.</p><p>(Applåder)</p>